---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: molecule/default/yamllint.yml
platforms:
  - name: centos-7
    image: milcom/centos7-systemd
    image_version: latest
    privileged: True
  - name: ubuntu-16.04
    image: ubuntu
    image_version: xenial
    privileged: True
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
  test_sequence:
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    #- idempotence
    #- side_effect
    - verify
    - destroy
verifier:
  name: testinfra
  lint:
    name: flake8
