---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: molecule/default/yamllint.yml
platforms:
  - name: CentOS
    image: solita/centos-systemd
    image_version: latest
    privileged: True
    command: '/sbin/init'
    security_opts:
      - seccomp=unconfined
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
  - name: Ubuntu
    image: solita/ubuntu-systemd
    image_version: latest
    privileged: True
    command: '/sbin/init'
    security_opts:
      - seccomp=unconfined
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
  test_sequence:
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    #- idempotence
    #- side_effect
    - verify
    - destroy
verifier:
  name: testinfra
  lint:
    name: flake8
